name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  percent_indicator: ^4.2.3
  json_annotation: ^4.8.1
  intl: ^0.19.0
  awesome_notifications: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

